### ISSUE TITLE
As a user, I want Moscow to support Moco Global setting format.

### ISSUE THREAD

**Issue by xin-pan** [macdao/moscow#2]
Moscow reads *.json under specified contract folders recursively. It is difficult to manage when there're too many *.json. It would be good if we can support Moco Global setting.
We only need the 2 features for the 1st step:
1. [Context](https://github.com/dreamhead/moco/blob/master/moco-doc/global-settings.md#context)
1. [File Root](https://github.com/dreamhead/moco/blob/master/moco-doc/global-settings.md#file-root)

**Comment by macdao** [comment]
I don't understand `It is difficult to manage when there're too many *.json`

Would you like to give more details?

**Comment by xin-pan** [comment]
In our Moco practice, we also use .json as a sample payload or a response body. e.g.: 
```  
{
    "description": "should_get_current_user",
    "request": {
      "method": "get",
      "uri": "/user"
    },
    "response": {
      "file": "user.json"
    }
  }
```
There're quite a lot of .json files. Moscow could not tell the difference between a moco config file and the other json files. When it reads a non-moco-config json file, exception occurs. 

That's why I say _It is difficult to manage when there're too many *.json_

Another reason I didn't mention is that we use the Moco Global setting frequently in our contract. It would be great if we can use Moscow without changing our existing contract.

**Comment by macdao** [comment]
got it. will support global setting.

**Comment by macdao** [comment]
see 0ee136accc32aef0a751eb404a1844e283fc554f

**Comment by xin-pan** [comment]
Fantastic! This feature has been used it in our project!
